INSERT INTO public.wilayas (code, name) VALUES
('01', 'Adrar'),
('02', 'Chlef'),
('03', 'Laghouat'),
('04', 'Oum El Bouaghi'),
('05', 'Batna'),
('06', 'BÃ©jaÃ¯a'),
('07', 'Biskra'),
('08', 'BÃ©char'),
('09', 'Blida'),
('10', 'Bouira'),
('11', 'Tamanrasset'),
('12', 'TÃ©bessa'),
('13', 'Tlemcen'),
('14', 'Tiaret'),
('15', 'Tizi Ouzou'),
('16', 'Alger'),
('17', 'Djelfa'),
('18', 'Jijel'),
('19', 'SÃ©tif'),
('20', 'SaÃ¯da'),
('21', 'Skikda'),
('22', 'Sidi Bel AbbÃ¨s'),
('23', 'Annaba'),
('24', 'Guelma'),
('25', 'Constantine'),
('26', 'MÃ©dÃ©a'),
('27', 'Mostaganem'),
('28', 'M''Sila'),
('29', 'Mascara'),
('30', 'Ouargla'),
('31', 'Oran'),
('32', 'El Bayadh'),
('33', 'Illizi'),
('34', 'Bordj Bou Arreridj'),
('35', 'BoumerdÃ¨s'),
('36', 'El Tarf'),
('37', 'Tindouf'),
('38', 'Tissemsilt'),
('39', 'El Oued'),
('40', 'Khenchela'),
('41', 'Souk Ahras'),
('42', 'Tipaza'),
('43', 'Mila'),
('44', 'AÃ¯n Defla'),
('45', 'NaÃ¢ma'),
('46', 'AÃ¯n TÃ©mouchent'),
('47', 'GhardaÃ¯a'),
('48', 'Relizane'),
('49', 'Timimoun'),
('50', 'Bordj Badji Mokhtar'),
('51', 'Ouled Djellal'),
('52', 'BÃ©ni AbbÃ¨s'),
('53', 'In Salah'),
('54', 'In Guezzam'),
('55', 'Touggourt'),
('56', 'Djanet'),
('57', 'El M''Ghair'),
('58', 'El Meniaa'),
('59', 'Aflou'),
('60', 'El Abiodh Sidi Cheikh'),
('61', 'El Aricha'),
('62', 'El Kantara'),
('63', 'Barika'),
('64', 'Bou SaÃ¢da'),
('65', 'Bir El Ater'),
('66', 'Ksar El Boukhari'),
('67', 'Ksar Chellala'),
('68', 'AÃ¯n Oussara'),
('69', 'Messaad')
ON CONFLICT (code) DO UPDATE 
SET name = EXCLUDED.name, active = true;
