// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { secureStorage } from '@/lib/secureStorage';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_ANON_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;

// Debug: Confirm connection environment
if (import.meta.env.DEV) {
  console.log("🔌 Supabase Client Connecting to:", SUPABASE_URL);
  if (SUPABASE_URL?.includes('supabase.co')) {
    console.warn("⚠️ WARNING: You are connecting to PRODUCTION Supabase in Development mode!");
  } else {
    console.log("✅ Connecting to LOCAL Supabase");
  }
}

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY, {
  auth: {
    storage: secureStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    flowType: 'implicit', // Changed from 'pkce' to fix email verification links
  }
});